team-peekabook/Peekabook-server-legacy

- prisma/schema.prisma
* closed #3 
* RDS 세팅
* Datagrip으로 RDS 잘 연결되는지 확인 완료
* RDS와 prisma 잘 연동 되는지 확인을 위해 User 테이블 생성해보기
* 이런 방식으로 작업하면 되는지 리드님 확인 부탁드려요 :)))
> #3 [setting] RDS와 prisma 연동

- package.json
- prisma/schema.prisma
- yarn.lock
* closed 
* [Setting] db setting
*
> #1 [Setting] db setting

- src/service/friendService.ts
* closed 
* [Fix] service - 추천한사람, 추천받은사람 수정
*
> #5 [Fix] service - 추천한사람, 추천받은사람 수정

- prisma/schema.prisma
- src/constants/responseMessage.ts
- src/controller/index.ts
- src/controller/recommendController.ts
- src/router/index.ts
- src/router/recommendRouter.ts
- src/service/friendService.ts
- src/service/index.ts
- src/service/recommendService.ts
* closed #6 
* 추천한책, 추천받은 책 조회
* 추천한책, 추천받은책 객체 포함하여 GET
> #6[feat] Get recommend book api

- src/constants/responseMessage.ts
- src/controller/friendController.ts
- src/router/friendRouter.ts
- src/service/friendService.ts
* closed #18 
* user search api 구현
* contain을 통해 한글자만 포함한 경우라도 조회하도록 설정
> #18 [Feat] user search api 구현

- src/service/friendService.ts
* closed 
* 검색 키워드 모두 포함해야 조회하도록 수정
* 조회시 전체 키워드 입력해야 조회하도록 설정
* contain-> 키워드 전체를 포함해야 조회하도록
> #18 [Fix] 검색 키워드 모두 포함해야 조회하도록 수정

- prisma/schema.prisma
- src/constants/responseMessage.ts
- src/controller/bookshelfController.ts
- src/controller/index.ts
- src/interfaces/bookshelf/BookshelfUpdateDTO.ts
- src/router/bookshelfRouter.ts
- src/service/bookshelfService.ts
* closed #17 
* 내 책장에 등록된 책 정보 수정하기
👇 api 요청 전 DB
👇 요청 잘 보내지는 것 확인 
👇 api 요청 후 DB
> #17 [Feat] bookshelf patch api

- prisma/schema.prisma
- src/constants/responseMessage.ts
- src/controller/bookshelfController.ts
- src/controller/index.ts
- src/router/bookshelfRouter.ts
- src/service/bookshelfService.ts
* closed #15 
* 책장에 등록한 책 삭제하기 
* userId와 bookId 두 가지 모두로 bookshelf 테이블에서 탐색해서 해당 유저의 책장 -> 해당 책을 삭제 해야함. _(현재는 userId 1로 고정)_
👇 해당 api request 전 DB
* 현재 유저 1의 책장에도 bookId가 3인 책이 저장 되어있고, 유저 2의 책장에도 저장되어 있음.
* 현재 유저는 userId가 1이라고 고정한다면 유저 1의 책장의 bookId가 3인 책만 삭제하는 상황이라고 가정한다.
👇 api 올바르게 요청되는 것 확인
👇 api request 후 올바르게 삭제된 DB
> #15 [Feat] bookshelf delete api

- src/constants/responseMessage.ts
- src/controller/friendController.ts
- src/router/friendRouter.ts
- src/service/friendService.ts
* closed #19 
* post follow api
`POST /friend/:friendId`
* senderId는 userID 1로 고정
> #19 [Feat] post follow api

- src/constants/responseMessage.ts
- src/controller/pickController.ts
- src/router/pickRouter.ts
- src/service/pickService.ts
* closed #29 
* pick뷰에서 책 전체조회 - get book api
* `GET - /pick/all
*
> #29 [Feat] get book api

- src/constants/responseMessage.ts
- src/controller/bookshelfController.ts
- src/interfaces/book/BookDTO.ts
- src/interfaces/bookshelf/BookshelfResDTO.ts
- src/interfaces/pick/PickBook.ts
- src/interfaces/user/UserDTO.ts
- src/router/bookshelfRouter.ts
- src/service/bookshelfService.ts
- src/service/index.ts
- src/service/userService.ts
* closed #24 
* 내 책장 페이지 (메인 뷰) 조회하기
*  section 1 ~4 로 나눠서 각 섹션마다 필요한 데이터를 전달했습니다용 ~
> #24 [Feat] bookshelf get api

- prisma/schema.prisma
- src/constants/responseMessage.ts
- src/controller/bookshelfController.ts
- src/interfaces/bookshelf/FriendBookshelfResDTO.ts
- src/interfaces/bookshelf/MyBookshelfResDTO.ts
- src/interfaces/user/IntroDTO.ts
- src/router/bookshelfRouter.ts
- src/service/bookshelfService.ts
* closed #25 
* 친구 책장 조회하기 api 구현
* 클라에서 조회할 친구의 userId를 path로 받아서 해당 친구의 책장을 조회할 수 있음
> #25 [Feat] bookshelf friend get api

- prisma/schema.prisma
- src/constants/responseMessage.ts
- src/controller/friendController.ts
- src/router/friendRouter.ts
- src/service/friendService.ts
* closed #36 
* 팔로우 취소하기 api 구현
* request 전 DB
* request 잘 되는지 확인
* request 후 DB -> 삭제 잘 되는 것 확인
> #36 [Feat] friend delete api

- prisma/schema.prisma
- src/service/bookshelfService.ts
* closed #38 
* 나를 팔로우 하는 친구들에게 알림 보내기 구현 완료
* 현재 유저 1을 팔로우 하는 사람이 유저 2, 유저 3, 유저 4 라고 가정
* 유저 1이 새로운 책을 등록함
* 알림 테이블에 새로운 데이터 추가됨
* 알림 받는 사람 (receiverId) 은 유저 1을 팔로우 한 유저 2, 유저 3, 유저 4가 됨.
* 알림 id 는 17, 18, 19 가 됨. 이 id를 newBookAlarm 테이블에서 FK로 참조함.
> #38 [Feat] 나를 팔로우하는 친구들에게 알림 보내기 구현 완료

- package-lock.json
- package.json
- prisma/schema.prisma
- src/constants/responseMessage.ts
- src/controller/alarmController.ts
- src/controller/index.ts
- src/interfaces/alarm/AlarmResponseDTO.ts
- src/router/alarmRouter.ts
- src/router/index.ts
- src/service/alarmService.ts
- src/service/index.ts
- yarn.lock
* closed #30 
* get alarm api
* 알림 3가지 경우 처리
* promise 객체 map으로 돌려서 type, alarmId에 따라 조회
> #30 [Feat] get alarm api

- src/service/friendService.ts
* closed #44 
* 친구가 나에게 책 추천했을 때 알림 추가하기 구현 완료
> #44 [Feat] 책 추천 알림 추가하기

- src/service/friendService.ts
* closed #42 
* 팔로우 할 때 알림 테이블에 데이터 추가하기 구현 완료
> #42 [Feat] 팔로우 알림 추가하기 구현 완료

- src/interfaces/recommend/RecommendGetDTO.ts
- src/router/recommendRouter.ts
- src/service/recommendService.ts
* closed #41 
* recommend 수정
* recommend 수정
> #41 [Fix] recommend

- prisma/schema.prisma
- src/interfaces/bookshelf/FriendBookshelfResDTO.ts
- src/interfaces/bookshelf/MyBookshelfResDTO.ts
- src/service/bookshelfService.ts
- src/service/userService.ts
* closed #48 
* UserDTO import문에 오타 수정
* 오늘의 교훈 : 한글자씩 잘 보자 ^^
> #48 [Fix] UserDTO import문 오타 수정

- src/interfaces/friend/FriendRecommendRequestDTO.ts
- src/service/friendService.ts
* closed #47 
*  fix deploy error
* String -> string 수정
* books null 타입 체크
> #47 [Fix] fix deploy error

- src/controller/friendController.ts
- src/interfaces/friend/SearchFriendResponseDTO.ts
- src/service/friendService.ts
* closed #51 
* fix search friend
* friend isFollowed response 추가
* 팔로우 안한경우 false 반환
> #51 [Fix] fix search friend

- package-lock.json
- package.json
- src/constants/responseMessage.ts
- src/controller/friendController.ts
- src/controller/pickController.ts
- src/interfaces/friend/FriendRecommendRequestDTO.ts
- src/modules/slackErrorMessage.ts
- src/modules/slackWebhook.ts
- src/service/friendService.ts
- yarn.lock
> [Add] slack webhook API 추가

- src/controller/pickController.ts
* closed #56 
* slack webhook api
*
> [feat] slack webhook api

- .husky/pre-commit
- package-lock.json
- package.json
- src/controller/bookshelfController.ts
- yarn.lock
* closed #54 
* husky 관련 코드 추가
> [Add] husky 관련 file 추가

- src/service/friendService.ts
* closed #58 
* [Fix] friendService 오타 수정
*
> [Fix] friendService 오타 수정

- .husky/pre-commit
- package-lock.json
- package.json
- src/controller/bookshelfController.ts
* closed #54 
* husky 잘 작동 되는지 확인 완료 이후 필요 없어진 코드 제거
> #54 [Add] add husky file

- .husky/pre-commit
- src/constants/responseMessage.ts
- src/controller/friendController.ts
- src/service/friendService.ts
- yarn.lock
* closed #65 
* 사용자 검색시 없는 유저인 경우 처리
* 친구 책 추천하는 경우 friendId가 내 친구 아닌 경우 처리
*
> #65 [Recactor] post recommend

- .husky/pre-commit
- src/constants/responseMessage.ts
- src/controller/friendController.ts
- src/interfaces/alarm/AlarmResponseDTO.ts
- src/service/alarmService.ts
- src/service/friendService.ts
- yarn.lock
* closed #67 
* refactor alarm response
* alarm response data 수정
* 유저 확인하여 데이터 수정
> [#67] Refactor alarm response

- src/controller/friendController.ts
* closed 
* response message 수정
*
> #67 [refactor] response message 수정

- src/controller/bookshelfController.ts
- src/service/bookshelfService.ts
* closed #71 
* GET bookshelf API의 response 형식 리팩토링
* 친구 책장 조회하기 API response 형식 리팩토링
* 친구 아이디가 올바르지 않을 경우도 분기처리
> #71 [Refactor] bookshelf get api

- src/constants/responseMessage.ts
- src/controller/friendController.ts
- src/service/friendService.ts
- src/service/pickService.ts
* closed #72 
* follow get 수정
* follow 하는 api 수정
*
> #72 [Refactor] api response 수정

- src/interfaces/book/BookDTO.ts
- src/service/bookshelfService.ts
* closed #70 
* bookshelfId 값도 response body에 추가
* 내 책장 조회, 친구 책장 조회 API 둘다 추가
> #70 [Refactor] bookshelfId 값도 response body에 추가

- src/service/recommendService.ts
* closed #78 
* #78 [Add] recommend api
* recommend profile Image 추가
> #78 [Add] recommend api

- src/controller/bookshelfController.ts
- src/service/bookshelfService.ts
* closed #75 
* 책 상세 정보 조회 API refactoring
* slack webhook 연동
* 404 에러 시 분기처리
> #75 [Refactor] 책 상세 정보 조회 API refactoring

- src/service/bookshelfService.ts
* closed #81 
* 메인 뷰 조회, 친구 책장 조회할 때 친구 목록 section 에서 id 값으로 정렬되도록 response 바꾸기
> #81 [Fix] 친구 목록 정렬

- src/controller/alarmController.ts
- src/controller/bookshelfController.ts
- src/controller/friendController.ts
- src/controller/pickController.ts
- src/controller/recommendController.ts
* closed #87 
*  user header 추가
*
> #87 [Add] user header

- src/controller/bookshelfController.ts
- src/service/bookshelfService.ts
> #83 [Refactor] 등록한 책 삭제 리팩토링

- src/controller/bookshelfController.ts
- src/service/bookshelfService.ts
* closed #90 
* request header 에서 유저 아이디 받는 코드 추가해서 유저 나누기 완료
> #90 [Add] request header 에서 유저 아이디 받는 코드 추가

- src/controller/pickController.ts
- src/service/recommendService.ts
* closed #98 
* #98 [Fix] recommend 최신순
*
> #98 [Fix] recommend 최신순

- test/friend.spec.ts
* closed 
*  friend test 형식수정
*
> #95 [Test] friend test 형식수정

- test/bookshelf.spec.ts
* closed #102 
* 책 상세 정보 조회 API 테스트 코드
- 테스트 코드 전체적인 코딩 컨벤션 지켜가며 했어요 ! 노션 확인하고 같이 맞추면 좋을 것 같습니다 ~
> #102 [Test] 책 상세 정보 조회 API 테스트 코드

- src/service/pickService.ts
* closed #112 
* #112 [Fix] pick 수정
*
> #112 [Fix] pick 수정

- test/recommend.spec.ts
* closed #109 
* [Test] recommend test
*
> #109 [Test] recommend test

- src/service/pickService.ts
- test/friend.spec.ts
- test/recommend.spec.ts
> #109 [Fix] pick최신순

- src/service/bookshelfService.ts
- test/bookshelf.spec.ts
* closed #103
* bookshelf - 책 삭제 API 테스트 코드
* 아직 '해당하는 책을 찾을 수 없습니다' 케이스에 대한 처리는 하지 않음..
> #103 [Test] bookshelf - 책 삭제 API 테스트 코드

- test/bookshelf.spec.ts
> #97 [Test] bookshelf test

- test/alarm.spec.ts
* closed #111 
* [Test] alarm test
*
> #111 [Test] alarm test

- test/bookshelf.spec.ts
> [Test] 등록한 책 상세 조회 API 테스트 코드

- test/bookshelf.spec.ts
> #103 [Test] 등록한 책 삭제 after 로직 추가

- test/bookshelf.spec.ts
* closed #104 
* 등록한 책 수정 테스트 코드 작성
*책 수정한 것 복구하기 위해 after 로직까지 구현
> #104 [Test] 등록한 책 수정 테스트 코드

- test/bookshelf.spec.ts
* closed #105 
* 내 책장 조회하기 테스트 코드
> #105 [Test] 내 책장 조회하기 테스트 코드

- test/pick.spec.ts
> #110 pick test

- test/bookshelf.spec.ts
- test/pick.spec.ts
* closed #106 
* [Test] 친구 책장 조회하기 테스트 코드 구현
*
> #106 [Test] 친구 책장 조회하기 테스트 코드 구현

- src/controller/bookshelfController.ts
> #128 [Add] 책 등록 시 response body에 data 추가

- test/bookshelf.spec.ts
- test/pick.spec.ts
> #110 [Test] pick patch 수정

- src/service/bookshelfService.ts
- test/bookshelf.spec.ts
> [Test] bookshelf 테스트 코드 점검

- test/bookshelf.spec.ts
> #110 pick patch 수정

- src/controller/bookshelfController.ts
- src/router/bookshelfRouter.ts
- src/service/bookshelfService.ts
> #133 [Fix] bookshelfid로 path param 변경

- src/service/bookshelfService.ts
> #133 [Fix] 정렬 기준 수정

- src/controller/bookshelfController.ts
- src/service/bookshelfService.ts
> #137 [Fix] path param명 수정

- test/bookshelf.spec.ts
> [Test] bookshelf 테스트 코드 작성

- src/service/friendService.ts
- test/friend.spec.ts
> #141 [Add] 대소문자 코드 수정

- src/service/bookshelfService.ts
> #142 [Fix] 책장 전체 조회 시 정렬 기준 수정

- src/service/bookshelfService.ts
* closed #145 
* pick한 책 삭제 시, 나머지 pick한 책 순위 변경
*
> #145 [Fix] pick한 책 삭제 시, 나머지 pick한 책 순위 변경

- prisma/schema.prisma
- src/service/bookshelfService.ts
- src/service/friendService.ts
* closed #148 
* 내 책장 (메인 뷰) 조회 API에서 friend 관련 service 분리
* friendService 에서 친구 리스트 가져오는 함수 구현해서 모듈화 처리 후 bookshelfService에서 사용하도록 분리했습니다 !!
*
> #148 [Refactor] 책장 service에서 friend 관련 service 분리

- .github/workflows/deploy.yml
- package.json
- scripts/after-deploy.sh
- src/service/bookshelfService.ts
- src/service/friendService.ts
- src/service/userService.ts
* closed #150 
* 친구 책장 조회 api에서 friend와 user 관련 로직 분리
* service에서는 관련있는 테이블에만 접근하도록 friendService와 userService에서 각각 함수로 모듈화 하였습니다! 
* bookshelf 에서는 직접 접근하지 않고, 각각 모듈을 가져다 쓸 수 있도록 로직을 분리하였습니다.
*
> [Refactor] 친구 책장 조회 api 

- src/service/bookshelfService.ts
* closed #152 
* 내 책장 조회 api 에서 user 디비에 접근하는 로직 분리했습니다 !
*
> [Refactor] 내 책장 조회 api user 관련 서비스 분리

- prisma/schema.prisma
* closed #156 
* updatedAt 컬럼을 null 값 허용으로 만들었으니까 schema.prisma 파일에서 updatedAt에 ? 붙여서 문법 맞도록 수정했습니다 ~
*
> [Fix] user 테이블 updatedAt 컬럼 추가 시, prisma 파일 수정

- src/controller/pickController.ts
* closed #155 
* fix pick code 
*
> [refactor] fix pick code

- prisma/schema.prisma
- src/interfaces/bookshelf/BookshelfCreateDTO.ts
- src/interfaces/friend/FriendRecommendRequestDTO.ts
- src/service/alarmService.ts
- src/service/bookService.ts
- src/service/bookshelfService.ts
- src/service/friendService.ts
- src/service/userService.ts
- test/bookshelf.spec.ts
- test/pick.spec.ts
* closed #159 
* 책 등록 시, 책 출판사 컬럼 추가하도록 코드 변경 완료.
* 책 추천 등 출판사 정보가 필요한 코드 모두 수정 완료 했습니다 ~~
* 테스트 코드도 지금 밀어버린 데이터에 맞게 수정 했습니다 !!
* bookshelf 서비스 리팩토링까지 완료 했습니다 ~~
*
> [Feat] 책 등록 시, 출판사 컬럼까지 저장

- .github/workflows/deploy.yml
- .vscode/settings.json
- package-lock.json
- package.json
- prisma/schema.prisma
- src/config/index.ts
- src/constants/responseMessage.ts
- src/controller/friendController.ts
- src/interfaces/friend/FriendReportRequestDTO.ts
- src/interfaces/friend/ReportMailRequestDTO.ts
- src/interfaces/friend/reportMailDTO.ts
- src/modules/mail.ts
- src/modules/reportMessage.ts
- src/router/friendRouter.ts
- src/service/friendService.ts
- test/friend.spec.ts
- test/pick.spec.ts
- yarn.lock
* closed #160 
* 신고하기 POST
* 픽수정 test 수정
* 신고하기 데이터 받았을 때 DB 저장
* 신고하기 test 구현
*  이메일로 전송 
**[이메일 전송을 위해 설정할 것!!!]**
* `npm i nodemailer` -> 모듈 설치하기
> #160 [Feat] post report

- test/friend.spec.ts
> #160 [feat] test code fix

- .github/workflows/deploy.yml
- package-lock.json
- package.json
- prisma/schema.prisma
- src/controller/alarmController.ts
- src/controller/authController.ts
- src/controller/bookshelfController.ts
- src/controller/friendController.ts
- src/controller/pickController.ts
- src/controller/recommendController.ts
- src/interfaces/alarm/AlarmResponseDTO.ts
- src/interfaces/auth/SignUpReqDTO.ts
- src/interfaces/user/UserCreateDTO.ts
- src/interfaces/user/UserDTO.ts
- src/middlewares/auth.ts
- src/middlewares/index.ts
- src/modules/jwtHandler.ts
- src/modules/slackErrorMessage.ts
- src/modules/social.ts
- src/router/authRouter.ts
- src/router/index.ts
- src/service/authService.ts
- src/service/index.ts
- test/pick.spec.ts
- yarn.lock
* closed #163 
* 소셜 로그인 - 카카오 구현 완료 했습니다 !
* 클라분들에게 카카오 엑세스 토큰 헤더로 받아서 jwt 토큰으로 바꾸는 작업 완료했구요, 회원가입까지 api 구현했습니다 ~
* 다만, 그 프로필 이미지는 일단 보류 하고 진행하라고 하셔서 프로필 이미지는 추가하지 않은 코드입니다 !
* 설치해야할 라이브러리들이 있습니다 ! 다음 명령어를 실행해주세요 !!
- ` yarn add express-validator && yarn add -D @types/express-validator`
-  ` yarn add jsonwebtoken && yarn add -D @types/jsonwebtoken`
> #163 [Feat] 카카오 소셜 로그인 및 회원가입 구현

- src/controller/authController.ts
- src/service/authService.ts
* closed #168 
* 회원 정보 입력을 하지 않고, 소셜 로그인을 한번 더 했을 시 response body로 isSignedUp 변수가 true로 가는 버그 수정 했습니다 !
* 여기에, 클라 분들이 요청하신 한줄 소개에 엔터 값을 스페이스 값으로 바꾸는 것까지 추가 했씁니다 ~~
*
> #168 [Fix] 카카오 소셜 로그인 시, 버그 수정

- src/constants/responseMessage.ts
- src/constants/userTokenCheck.ts
- src/controller/index.ts
- src/controller/userController.ts
- src/interfaces/user/UserDuplicateDTO.ts
- src/router/index.ts
- src/router/userRouter.ts
- src/service/userService.ts
- yarn.lock
* closed #165 
* 유저 아이디 중복 검사
* 유저 토큰으로 id 조회하는 constants 파일 만들었습니다.
* 만료된 토큰일때와 유효하지 않은 토큰을 모든 함수에 적용해야하는데 모듈로 빼서 더 깔끔하고 재활용적으로 사용할 수 있는 방법을 더 찾아봐야할 것 같습니다
> #165 [Feat] post - check user nickname

- src/controller/index.ts
- src/controller/mypageController.ts
- src/router/index.ts
- src/router/mypageRouter.ts
- src/service/index.ts
- src/service/mypageService.ts
> #166 [feat] delete user

- .github/workflows/deploy.yml
- package-lock.json
- package.json
- src/config/s3Config.ts
- src/controller/mypageController.ts
- src/interfaces/mypage/patchUserRequestDTO.ts
- src/middlewares/index.ts
- src/middlewares/upload.ts
- src/router/mypageRouter.ts
- src/service/mypageService.ts
- yarn.lock
* closed #172 
* 프로필 수정 (multipart-form)
* 사진과 같이 Form에 데이터들 입력하면 됩니다
* any 타입 확인
1. env파일에 key값 넣기
2. 세미나 보고 s3 종속성 다운 받기 (머 삭제하고 지워야해서 세미나 보는게 더나을 것 같습니다!)
> #172 [feat] fix user profile

- src/constants/responseMessage.ts
- src/controller/authController.ts
- src/modules/jwtHandler.ts
- src/router/authRouter.ts
- src/service/authService.ts
- src/service/userService.ts
* closed #173 
* 만료된 토큰을 재발급합니다.
* accessToken만 만료되었다면, 클라가 넘겨준 refreshToken을 이용해서 accessToken 재발급해서 내려줌
* accessToken과 refreshToken이 모두 만료가 되었다면 에러코드와 메세지로 재로그인을 요청
*
> #173 [Feat] 토큰 만료 시, 토큰 재발급 구현

- src/constants/responseMessage.ts
- src/controller/mypageController.ts
- src/interfaces/user/IntroDTO.ts
- src/router/mypageRouter.ts
- src/service/userService.ts
> #178 [feat] get user data

- src/controller/authController.ts
- src/modules/social.ts
- src/service/authService.ts
* closed #176 
* 애플 로그인 구현 했습니다 !
* 애플 서버에서 공개키 받아와서 클라가 헤더로 보낸 identityToken 해독하여 jwt로 변환
*
> #176 [Feat] 소셜 애플 로그인 구현

- src/constants/responseMessage.ts
- src/controller/friendController.ts
- src/middlewares/auth.ts
- src/modules/jwtHandler.ts
- src/router/friendRouter.ts
- src/service/friendService.ts
- test/friend.spec.ts
* closed #174 
* 친구 차단 api 구현했습니다 ~~
* 이슈에 적어놓은 분기 처리까지 완료 했습니다 !!
* env 파일에 test access token 키 값 추가해서 실행하셔야 합니다 !
> #174 [Feat] 친구 차단하기 

- src/controller/alarmController.ts
- src/controller/friendController.ts
- src/controller/mypageController.ts
- src/controller/pickController.ts
- src/controller/recommendController.ts
- src/controller/userController.ts
- src/router/alarmRouter.ts
- src/router/friendRouter.ts
- src/router/mypageRouter.ts
- src/router/pickRouter.ts
- src/router/recommendRouter.ts
- test/alarm.spec.ts
- test/friend.spec.ts
- test/pick.spec.ts
- test/recommend.spec.ts
> #188 [refactor] auth 수정

- .github/workflows/deploy.yml
- package.json
- src/controller/authController.ts
- src/router/authRouter.ts
- src/service/authService.ts
- yarn.lock
> #190 [Add] 회원 가입 시, 프로필 이미지 등록

- prisma/schema.prisma
- src/service/friendService.ts
* closed #193 
* cascade한 prisma 파일까지 같이 올렸습니다 ~
*
> #193 [Fix] 사용자가 자신의 닉네임으로 사용자 검색 시, 안되도록 수정

- src/controller/bookshelfController.ts
- src/controller/friendController.ts
- src/controller/mypageController.ts
> #194 [Refactor] 글을 입력하는 모든 칸에서, 줄바꿈 제거 데이터 전처리

- src/router/mypageRouter.ts
> #197 [Fix]  patch user

- src/controller/authController.ts
- src/controller/mypageController.ts
> #199 [Fix] 닉네임에 공백 제거

- src/controller/userController.ts
> #201 [Fix] 닉네임 중복 검사 시, 공백 제거 후 검사

- src/controller/authController.ts
- src/modules/jwtHandler.ts
> #203 [Chore] 테스트를 위해 토큰 유효기간 변경

- src/modules/jwtHandler.ts
> #205 [Chore] 토큰 유효기간 변경

- src/constants/responseMessage.ts
- src/controller/friendController.ts
- src/service/friendService.ts
- test/friend.spec.ts
* closed #214 
* 신고시 친구인 사람만 적용가능하도록 수정
* response message 수정
*
> #214 [refactor] code fix

- src/constants/responseMessage.ts
- src/controller/authController.ts
- src/controller/bookshelfController.ts
- src/controller/friendController.ts
- src/controller/mypageController.ts
- src/middlewares/auth.ts
- src/service/authService.ts
- src/service/friendService.ts
> #213 [Refactor] 예슬 담당 api response body 리팩토링

- .vscode/settings.json
- src/service/alarmService.ts
- src/service/bookshelfService.ts
* closed #221 
* 알림 내림차순 수정
* 책 삭제시 알림 디비에서도 삭제
*
> #221 [fix] alarm fix

- src/service/alarmService.ts
> [FIX] 친구 차단 시, 양쪽에서 알림 삭제

- src/service/userService.ts
* closed #225 
* 닉네임 중복 검사 시, 대소문자 구분 없도록 수정했습니다.
*
> #225 [Fix] 닉네임 중복 검사 시, 대소문자 구분 없도록 수정

- src/index.ts
> #229 [feat] version add

- src/controller/userController.ts
- src/router/userRouter.ts
- src/service/userService.ts
* closed #234 
* 강제 업데이트 버전 받아오는 api 통신 시에 토큰 검증 로직 제거했습니다.
*
> [feat] #234 강제 업데이트 버전 확인 시, 토큰 검증 로직 제거

- prisma/schema.prisma
> prisma 연동 이슈 대응

- prisma/schema.prisma
> [FIX] prisma 누락된 부분 추가

- .gitignore
- src/config/pushConfig.ts
- src/service/alarmService.ts
- src/service/friendService.ts
> [CHORE] #249 푸시 알림 텍스트 변경

- src/service/alarmService.ts
- src/service/friendService.ts
> [FIX] 푸시 알림 텍스트 잘못된 변수 수정

- .dockerignore
- .gitignore
- docker/Dockerfile.dev
- docker/Dockerfile.prod
- docker/docker-compose.dev.yml
- docker/docker-compose.prod.yml
- package.json
- src/config/index.ts
- src/index.ts
- yarn.lock
* closed #259 
* docker로 node 띄울 수 있게 세팅 했습니다.
*
> #259 [INFRA] docker-compose로 배포할 수 있는 환경 세팅
